USE OrganTransplantDB;
SELECT 'Q1  O+ donors'                   AS Query, COUNT(*) AS row_count FROM Donor WHERE Blood_group = 'O+';
SELECT 'Q2  Available organs'            AS Query, COUNT(*) AS row_count FROM Organ WHERE Status = 'Available';
SELECT 'Q3  Recipients by urgency'       AS Query, COUNT(*) AS row_count FROM Recipient;
SELECT 'Q4  Multi-organ donors'          AS Query, COUNT(*) AS row_count FROM (SELECT Donor_ID, COUNT(*) c FROM Organ GROUP BY Donor_ID HAVING c >= 2) t;
SELECT 'Q5  Avg compatibility'           AS Query, ROUND(AVG(Compatibility_Score),2) AS row_count FROM Match_Record;
SELECT 'Q6  Hospitals w/ success'        AS Query, COUNT(DISTINCT h.H_ID) AS row_count FROM Hospital h JOIN Match_Record mr ON h.H_ID = mr.Hospital_ID JOIN Surgery_Record s ON mr.M_ID = s.Match_ID WHERE s.Outcome = 'Successful';
SELECT 'Q7  Organs with donor'           AS Query, COUNT(*) AS row_count FROM Organ o JOIN Donor d ON o.Donor_ID = d.D_ID;
SELECT 'Q8  Matches with recipient'      AS Query, COUNT(*) AS row_count FROM Match_Record mr JOIN Recipient r ON mr.Recipient_ID = r.R_ID;
SELECT 'Q9  Full chain of custody'       AS Query, COUNT(*) AS row_count FROM Match_Record mr JOIN Organ o ON mr.Organ_ID = o.O_ID JOIN Donor d ON o.Donor_ID = d.D_ID JOIN Recipient r ON mr.Recipient_ID = r.R_ID JOIN Hospital h ON mr.Hospital_ID = h.H_ID;
SELECT 'Q10 Ready-to-allocate organs'    AS Query, COUNT(*) AS row_count FROM Organ o JOIN Donor d ON o.Donor_ID = d.D_ID JOIN Consent_Document cd ON d.D_ID = cd.Donor_ID WHERE o.Status = 'Available' AND d.Is_Alive = TRUE AND cd.Approval_Status = 'Approved';
SELECT 'Q11 Above-avg urgency recip'     AS Query, COUNT(*) AS row_count FROM Recipient WHERE Medical_Urgency_Score > (SELECT AVG(Medical_Urgency_Score) FROM Recipient);
SELECT 'Q12 Donors w/ approved consent' AS Query, COUNT(*) AS row_count FROM Donor d WHERE EXISTS (SELECT 1 FROM Consent_Document cd WHERE cd.Donor_ID = d.D_ID AND cd.Approval_Status = 'Approved');
SELECT 'Q13 Recipient match status'      AS Query, COUNT(*) AS row_count FROM Recipient;
SELECT 'Q14 Mark allocated->used'        AS Query, COUNT(*) AS row_count FROM Organ o JOIN Match_Record mr ON o.O_ID = mr.Organ_ID JOIN Surgery_Record s ON mr.M_ID = s.Match_ID WHERE s.Outcome = 'Successful' AND o.Status = 'Allocated';
SELECT 'Q15 Old rejected consent docs'   AS Query, COUNT(*) AS row_count FROM Consent_Document WHERE Approval_Status = 'Rejected' AND Upload_Date < DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR);
